name: Build and Deploy Backend API

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask app
      working-directory: ./backend
      run: |
        python -c "from app import app; print('✅ Backend API ready for deployment')"

    - name: Build Docker image (optional)
      run: |
        echo "📦 Docker image can be built here for containerized deployment"
        echo "   Example: docker build -t expense-tracker-api ./backend"

    - name: Deployment Information
      run: |
        echo "🚀 Backend is ready for deployment!"
        echo "💡 Deployment options:"
        echo "   - Heroku: git push heroku main"
        echo "   - Railway: railway deploy"
        echo "   - Render: Connect GitHub repo for auto-deploy"
        echo "   - DigitalOcean: Use App Platform"
